doctrine:
  orm:
    mappings:
      AuditRequestBundle:
        dir: '/Domain/'
        prefix: DMP\AuditRequestBundle\Domain
        is_bundle: true
        type: attribute
  dbal:
    types:
      !php/const DMP\AuditRequestBundle\Infrastructure\Doctrine\AuditRequestIdType::NAME: DMP\AuditRequestBundle\Infrastructure\Doctrine\AuditRequestIdType
